DROP DATABASE IF EXISTS familydoctor;
CREATE DATABASE familydoctor;
USE familydoctor;

CREATE TABLE Address(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  STREET VARCHAR(100),
  CITY VARCHAR(100),
  STATE VARCHAR(100),
  ZIP VARCHAR(5) NOT NULL
) AUTO_INCREMENT = 100;

CREATE TABLE User(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  EMAIL VARCHAR(320) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  ENABLED BOOLEAN NOT NULL
) AUTO_INCREMENT = 100;

CREATE TABLE Patient(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  FIRST_NAME VARCHAR(10) NOT NULL,
  LAST_NAME VARCHAR(10) NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  GENDER ENUM('MALE', 'FEMALE') NOT NULL,
  PHONE VARCHAR(12) NOT NULL,
  SSN VARCHAR(4) NOT NULL,
  ADDRESS_ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  FOREIGN KEY (ADDRESS_ID) REFERENCES Address(ID),
  FOREIGN KEY (USER_ID) REFERENCES User(ID)
) AUTO_INCREMENT = 100;

CREATE TABLE Doctor(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  FIRST_NAME VARCHAR(10) NOT NULL,
  LAST_NAME VARCHAR(10) NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  GENDER ENUM('MALE', 'FEMALE') NOT NULL,
  PHONE VARCHAR(12) NOT NULL,
  SPECIALIZATION ENUM('CARDIOLOGIST', 'DENTIST', 'ENT', 'GYNECOLOGIST', 'PEDIATRICIAN', 'UROLOGIST', 'HEMATOLOGIST', 'HEPATOLOGIST') NOT NULL,
  LICENSE_NUMBER VARCHAR(10) NOT NULL,
  ADDRESS_ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  FOREIGN KEY (ADDRESS_ID) REFERENCES Address(ID),
  FOREIGN KEY (USER_ID) REFERENCES User(ID)
) AUTO_INCREMENT = 100;

CREATE TABLE Admin(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  STAFF_NUMBER INTEGER NOT NULL,
  FIRST_NAME VARCHAR(10) NOT NULL,
  LAST_NAME VARCHAR(10) NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  GENDER ENUM('MALE', 'FEMALE') NOT NULL,
  PHONE VARCHAR(12) NOT NULL,
  ADDRESS_ID INTEGER NOT NULL,
  USER_ID INTEGER NOT NULL,
  FOREIGN KEY (ADDRESS_ID) REFERENCES Address(ID),
  FOREIGN KEY (USER_ID) REFERENCES User(ID)
) AUTO_INCREMENT = 100;

CREATE TABLE Appointment(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ROOM VARCHAR(100) NOT NULL,
  DATE DATE NOT NULL,
  TIME VARCHAR(10) NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
  STATUS ENUM('NEW', 'ACCEPTED', 'REJECTED', 'COMPLETED', 'CANCELED') NOT NULL,
  INVOICE_ID INTEGER NOT NULL,
  PATIENT_ID INTEGER NOT NULL,
  DOCTOR_ID INTEGER NOT NULL
) AUTO_INCREMENT = 100;

CREATE TABLE Invoice(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  AMOUNT DOUBLE DEFAULT NULL,
  STATUS ENUM('NEW', 'PENDING', 'PAID') NOT NULL,
  CCARD_4DIGITS VARCHAR(4) NOT NULL,
  DATE_CREATED DATE NOT NULL,
  DATE_PAID DATE NOT NULL,
  APPOINTMENT_ID INTEGER NOT NULL,
  FOREIGN KEY (APPOINTMENT_ID) REFERENCES Appointment(ID)
) AUTO_INCREMENT = 100;

CREATE TABLE Authority(
  ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  EMAIL VARCHAR(30) NOT NULL,
  AUTHORITY ENUM('ROLE_PATIENT', 'ROLE_DOCTOR', 'ROLE_ADMIN') NOT NULL
) AUTO_INCREMENT = 100;


ALTER TABLE Appointment ADD FOREIGN KEY (INVOICE_ID) REFERENCES Invoice(ID);
ALTER TABLE Appointment ADD FOREIGN KEY (PATIENT_ID) REFERENCES Patient(ID);
ALTER TABLE Appointment ADD FOREIGN KEY (DOCTOR_ID) REFERENCES Doctor(ID);
